"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import type { NegotiationMessage } from "@/lib/database.types";
import { formatPrice } from "@/lib/listings";
import { acceptOffer, declineOffer, loadConversationMessages, loadConversationSummaries, makeCounterOffer, markConversationRead, reopenBookedListing, restoreDeclinedOffer, sendNegotiationMessage, undoAcceptedOffer, type ConversationSummary } from "@/lib/negotiations";
import { LISTING_IMAGE_PLACEHOLDER } from "@/lib/listing-image-consumers";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { createBrowserListingImageStorage } from "@/lib/storage/browser-listing-image-storage";

function relativeTime(iso: string) { const minutes = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 60000)); return minutes < 1 ? "now" : minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.round(minutes / 60)}h` : `${Math.round(minutes / 1440)}d`; }

function ConversationRow({ summary, selected, onSelect, cover }: { summary: ConversationSummary; selected: boolean; onSelect: () => void; cover: string }) {
  const preview = summary.latestMessage?.kind === "offer" ? `Offer: ${formatPrice(summary.latestMessage.offer_amount_inr ?? 0)}` : summary.latestMessage?.body ?? "Negotiation started";
  return <button type="button" className={`conversation-row ${selected ? "selected" : ""}`} onClick={onSelect}><img src={cover} alt="" /><span className="conversation-row-main"><strong>{summary.listing.make} {summary.listing.model}</strong><span>{summary.otherName}</span><span className="conversation-preview">{preview}</span></span><span className="conversation-meta"><time>{relativeTime(summary.last_message_at)}</time>{summary.unreadCount > 0 && <b>{summary.unreadCount}</b>}<em className={summary.status}>{summary.status === "agreed" ? "Booked" : summary.status}</em></span></button>;
}

function Thread({ summary, messages, refresh }: { summary: ConversationSummary; messages: NegotiationMessage[]; refresh: () => Promise<void> }) {
  const { user } = useAuth(); const [body, setBody] = useState(""); const [offer, setOffer] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  const locked = summary.status === "locked" || summary.listing.status === "deleted";
  async function run(action: () => Promise<unknown>) { setPending(true); setError(null); try { await action(); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "That action could not be completed."); } finally { setPending(false); } }
  async function submitMessage(event: FormEvent) { event.preventDefault(); if (!body.trim()) return; await run(async () => { await sendNegotiationMessage(summary.id, body.trim()); setBody(""); }); }
  async function submitOffer(event: FormEvent) { event.preventDefault(); const amount = Number(offer); if (!Number.isInteger(amount) || amount <= 0) { setError("Enter a whole offer amount greater than zero."); return; } await run(async () => { await makeCounterOffer(summary.id, amount); setOffer(""); }); }
  return <section className="negotiation-thread"><header className="thread-header"><Link href={`/listings/${summary.listing.id}`}><span>{summary.listing.make} {summary.listing.model}</span><small>{formatPrice(summary.listing.price_inr)} · {summary.listing.status === "booked" ? "Booked" : "Asking price"}</small></Link><span>{summary.otherName}</span></header><div className="message-history" aria-live="polite">{messages.map((message) => { const own = message.sender_id === user?.id; if (message.kind === "offer") return <div className={`offer-message ${own ? "own" : ""}`} key={message.id}><span>{own ? "You offered" : `${summary.otherName} offered`}</span><strong>{formatPrice(message.offer_amount_inr ?? 0)}</strong><small className={message.offer_status ?? ""}>{message.offer_status}</small>{message.offer_status === "pending" && !locked && <span className="offer-actions">{!own && user?.id === summary.seller_id && <button disabled={pending} onClick={() => void run(() => acceptOffer(message.id))}>Accept</button>}<button disabled={pending} className="text-button" onClick={() => void run(() => declineOffer(message.id))}>Decline</button></span>}{message.offer_status === "declined" && message.offer_resolved_by === user?.id && !locked && <button disabled={pending} className="text-button offer-undo" onClick={() => void run(() => restoreDeclinedOffer(message.id))}>Undo decline</button>}{message.offer_status === "accepted" && user?.id === summary.seller_id && <button disabled={pending} className="text-button offer-undo" onClick={() => void run(() => undoAcceptedOffer(message.id))}>Undo acceptance</button>}</div>; return <div className={`chat-message ${own ? "own" : ""}`} key={message.id}>{message.body}<small>{relativeTime(message.created_at)}</small></div>; })}</div>{locked ? <p className="thread-locked">{summary.listing.status === "deleted" ? "This listing was deleted. This history is read-only." : "This negotiation is closed."}</p> : <div className="thread-composers"><form onSubmit={submitOffer} className="counter-form"><input aria-label="Counteroffer amount" inputMode="numeric" value={offer} onChange={(event) => setOffer(event.target.value.replace(/[^0-9]/g, ""))} placeholder="Counteroffer ₹" /><button disabled={pending}>Offer</button></form><form onSubmit={submitMessage} className="message-form"><textarea aria-label="Message" rows={2} maxLength={2000} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a message" /><button className="button" disabled={pending}>Send</button></form>{summary.status === "agreed" && user?.id === summary.seller_id && <button className="text-button" disabled={pending} onClick={() => void run(() => reopenBookedListing(summary.listing.id))}>Sale fell through? Reopen listing</button>}{error && <p className="form-alert error">{error}</p>}</div>}</section>;
}

export function MessagesInbox() {
  const { user, loading } = useAuth(); const router = useRouter(); const params = useSearchParams(); const [summaries, setSummaries] = useState<ConversationSummary[]>([]); const [messages, setMessages] = useState<NegotiationMessage[]>([]); const [covers, setCovers] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(true); const selectedId = params.get("conversation") ?? summaries[0]?.id ?? null;
  const load = useCallback(async () => { if (!user) return; setBusy(true); try { const next = await loadConversationSummaries(user.id); setSummaries(next); const imageRows = await Promise.all(next.map(async (summary) => { try { const images = await createBrowserListingImageStorage().list(summary.listing_id); return [summary.listing_id, images.sort((a, b) => a.position - b.position)[0]?.publicUrl ?? LISTING_IMAGE_PLACEHOLDER] as const; } catch { return [summary.listing_id, LISTING_IMAGE_PLACEHOLDER] as const; } })); setCovers(Object.fromEntries(imageRows)); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Negotiations could not load."); } finally { setBusy(false); } }, [user]);
  const refreshThread = useCallback(async () => { if (!selectedId) return; const [next] = await Promise.all([loadConversationMessages(selectedId), markConversationRead(selectedId)]); setMessages(next); await load(); window.dispatchEvent(new Event("revvbase:conversations-changed")); }, [selectedId, load]);
  useEffect(() => { if (user) void load(); }, [user, load]);
  useEffect(() => { if (selectedId) void refreshThread(); }, [selectedId, refreshThread]);
  useEffect(() => { if (!selectedId) return; const channel = getSupabaseBrowserClient().channel(`conversation-${selectedId}`).on("postgres_changes", { event: "*", schema: "public", table: "negotiation_messages", filter: `conversation_id=eq.${selectedId}` }, () => void refreshThread()).on("postgres_changes", { event: "UPDATE", schema: "public", table: "listing_conversations", filter: `id=eq.${selectedId}` }, () => void refreshThread()).subscribe(); return () => { void getSupabaseBrowserClient().removeChannel(channel); }; }, [selectedId, refreshThread]);
  if (loading || busy) return <div className="shell page-section"><div className="state-panel" role="status">Loading negotiations…</div></div>;
  if (!user) return <div className="shell page-section"><div className="state-panel"><p className="eyebrow">Sign in required</p><h1>See your negotiations</h1><Link className="button" href="/auth?next=/messages">Continue to sign in</Link></div></div>;
  const selected = summaries.find((summary) => summary.id === selectedId);
  return <div className={`shell page-section inbox-page ${selected ? "thread-selected" : ""}`}><div className="inbox-heading"><div><p className="eyebrow">Messages</p><h1>Negotiations</h1></div><span>{summaries.reduce((total, row) => total + row.unreadCount, 0)} unread</span></div>{error ? <div className="state-panel compact" role="alert"><p>{error}</p><button className="button button-secondary" onClick={() => void load()}>Try again</button></div> : !summaries.length ? <div className="state-panel compact"><h3>No negotiations yet</h3><p>Make an offer from a vehicle listing to start one.</p><Link className="button" href="/">Browse vehicles</Link></div> : <div className="inbox-layout"><aside className="conversation-list" aria-label="Your conversations">{summaries.map((summary) => <ConversationRow key={summary.id} summary={summary} selected={summary.id === selectedId} cover={covers[summary.listing_id] ?? LISTING_IMAGE_PLACEHOLDER} onSelect={() => router.push(`/messages?conversation=${summary.id}`)} />)}</aside>{selected && <Thread summary={selected} messages={messages} refresh={refreshThread} />}</div>}</div>;
}
